# 设置用户密码过期时间
- name: set users password valid time
  shell: chage -M 90 "{{ item }}"
  with_items: 
    - "{{ users }}"

# 设置用户密码过期提醒时间
- name: set users password warning days
  shell: chage -W 30 "{{ item }}"
  with_items: 
    - "{{ users }}"

# 修改添加用户时默认配置密码过期天数
- name: modify /etc/login.defs PASS_MAX_DAYS
  lineinfile:
    path: /etc/login.defs
    regexp: 'PASS_MAX_DAYS'
    line: 'PASS_MAX_DAYS   90'

# 修改默认添加用户的密码长度
- name: modify /etc/login.defs PASS_MIN_LEN
  lineinfile:
    path: /etc/login.defs
    regexp: 'PASS_MIN_LEN'
    line: 'PASS_MIN_LEN    12'

# 修改密码过期提醒时间
- name: modify /etc/login.defs PASS_WARN_AGE
  lineinfile:
    path: /etc/login.defs
    regexp: 'PASS_WARN_AGE'
    line: 'PASS_WARN_AGE  30'
